apiVersion: v1
kind: Pod
metadata: 
  name: my-app
  labels:
    app: db
spec:
  containers:
    - name: my-nginx-wep-app
      image: ma7rouus/progect-os2
      imagePullPolicy: IfNotPresent
      ports:
        - containerPort: 80