apiVersion: v1
kind: Deployment
metadata: 
  name: myapp
spec: 
  replicas: 2

  selector:
    matchLabels:
      app: my-wep-app

  template:
    metadata:
      name: my-web-app
      labels:
        app: my-wep-app
    spec:
      containers:
        - name: custom-image
          image: ma7rouus/project
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 80           